### ISSUE TITLE
area and perimeter for Square are already implemented in Reactangle parent class.

### ISSUE THREAD

**Issue by igavrysh** [SCherkasov/MyPlayground#10]
https://github.com/SCherkasov/MyPlayground/blob/fe756032dfaee9036bac01f1014a2dc8c1c4e554/MyPlayground.playground/Contents.swift#L56-L63

Remove unnecessary code.

**Comment by SCherkasov** [comment]
fixed with you yesterday

**Comment by igavrysh** [comment]
Close issues by yourself
