### ISSUE TITLE
You should not store side variable in Square class, take it from parent class, Rectangle

### ISSUE THREAD

**Issue by igavrysh** [SCherkasov/MyPlayground#11]
https://github.com/SCherkasov/MyPlayground/blob/fe756032dfaee9036bac01f1014a2dc8c1c4e554/MyPlayground.playground/Contents.swift#L49-L54

1. Read article an https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html
What access type should height and width variables have, so that they are accessable from child class only?
2. Make side a calculatable property with only getter e.g. `var side: Float { get{ .... } }`
3. Make side a calculatable prop.... Add setter. e.g. `var side: Float { get{....} set {....}}`
4. Remove side assigning from `Square.init`

**Comment by SCherkasov** [comment]
fixed with you yesterday

**Comment by igavrysh** [comment]
please, close issues by yourself as long as you push code into repo for this fix
