### ISSUE TITLE
Whenever you use object variable inside its class, always use self.variable_name reference

### ISSUE THREAD

**Issue by igavrysh** [SCherkasov/MyPlayground#6]
https://github.com/SCherkasov/MyPlayground/blob/fe756032dfaee9036bac01f1014a2dc8c1c4e554/MyPlayground.playground/Contents.swift#L38-L39

This is my own rule so I advice to adhere to it.

If you don't like this style you can close this issue with tag - WILL NOT FIX

**Comment by SCherkasov** [comment]
fixed it)
