### ISSUE TITLE
Square is a Rectangle with width equal height, remove hardcoding for "2" value

### ISSUE THREAD

**Issue by igavrysh** [SCherkasov/MyPlayground#7]
https://github.com/SCherkasov/MyPlayground/blob/fe756032dfaee9036bac01f1014a2dc8c1c4e554/MyPlayground.playground/Contents.swift#L53

**Comment by SCherkasov** [comment]
fixed

**Comment by igavrysh** [comment]
Commit, push and only after that close issue

**Comment by SCherkasov** [comment]
fixed
