### ISSUE TITLE
Make area and perimeter as calculable properties, with getters

### ISSUE THREAD

**Issue by igavrysh** [SCherkasov/MyPlayground#8]
https://github.com/SCherkasov/MyPlayground/blob/fe756032dfaee9036bac01f1014a2dc8c1c4e554/MyPlayground.playground/Contents.swift#L7-L8

I expect something like 
```
class Shape {
  var area: Float { get }
  var perimeter: Float { get }
}
```

**Comment by SCherkasov** [comment]
smthng like this?

class Squere: Rectangle {
    
    private var side: Float
    
    init(side: Float) {
        
        self.side = side
        super.init(height: side, width: side)
    }
    
    var areaa: Float {
        get {
            return pow(self.side, 2)
        }
    }
    
    var perimeter: Float {
        get {
            return 4 * self.side
        }
    }
}

**Comment by igavrysh** [comment]
yes and no,

- pls fix areaa
- you don't need this props at all in Square, they will be automatically calculated in its parent Rectangle
- you should change Shape protocol, add there calculable props and remove functions
- you should change Rectangle class so that it should have perimeter and area as calculable properties

**Comment by SCherkasov** [comment]
I think fixed)

**Comment by igavrysh** [comment]
Close issue as soon as you feel it can be closed
